### ISSUE TITLE
impute.boot / impute.Lubin not working when Z = NULL

### ISSUE THREAD

**Issue by moosterwegel** [phargarten2/miWQS#3]
First of all, thank you for this great package that makes interesting and useful methods from the literature easy to implement. Much appreciated. 

I encountered an issue today with `impute.boot` when Z has its default value of NULL. I think it worked perfectly for me two months ago (different package version perhaps)? Anyway, here's a minimally reproducible example based on the example from the vignette:

```r
library('miWQS')
data("simdata87")

set.seed(23234)
X = simdata87$X.bdl[, 1]
DL = simdata87$DL[1]

# this works fine
l <- impute.boot(
  X = X, 
  DL = DL,
  Z = simdata87$Z.sim[, 1], 
  K = 5
) 

# this does not
l <- impute.boot(
  X = X, 
  DL = DL,
  Z = NULL, 
  K = 5
)

# Error in if (total.miss == 0) { : missing value where TRUE/FALSE needed
#   In addition: Warning messages:
#    1: In runif(n, unif_lower, unif_upper) : NAs produced
#   2: In runif(n, unif_lower, unif_upper) : NAs produced
#   3: In runif(n, unif_lower, unif_upper) : NAs produced
#   4: In runif(n, unif_lower, unif_upper) : NAs produced
#   5: In runif(n, unif_lower, unif_upper) : NAs produced
```

Any idea what goes wrong? I managed to replicate this on multiple machines. 

Thank you.

**Comment by phargarten2** [comment]
Paul, 
I hope all is well.

I came across your R code for impute.boot (miWQS) on github (https://github.com/cran/miWQS/blob/master/R/impute_boot.R). Thank you for this! I have been trying to use impute.boot for one of my projects and am encountering an error when I set Z=NULL. This is the error message I get:


When looking into this, I saw that some other users may be experiencing the same problem. I am wondering if you have encountered any issues like this and if you might have any suggestions as to how to resolve this error?

Any guidance would be much appreciated.

Best wishes,
Meaghan

**Comment by phargarten2** [comment]
Sorry for the delay; I had a medical issue this summer that has kept me away from this error. I feel better now. Thank you for your hard work in finding this problem. 

Using `r impute.Lubin()` with `verbose = TRUE` on the above code yields:
```
Dataset Used in Survival Model 
  id     chemcol2 event LB        UB Z
1  1   9073.36639     1  0 0.9244609 1
2  2 224890.28725     1  0 0.9244609 1
3  3     27.53743     1  0 0.9244609 1
4  4   2876.39150     1  0 0.9244609 1
5  5   1713.19866     1  0 0.9244609 1
6  6  85426.65652     1  0 0.9244609 1
Call:
survival::survreg(formula = my.surv.object ~ ., data = final[, 
    -(1:5), drop = FALSE], weights = my.weights, dist = "lognormal", 
    x = TRUE)

Coefficients: (1 not defined because of singularities)
(Intercept)           Z 
   4.732139          NA 

Scale= 4.088513 

Loglik(model)= -7608.4   Loglik(intercept only)= -7608.4
	Chisq= 0 on 1 degrees of freedom, p= 1 
n= 633 
Z: 
     [,1]
[1,]    1
[2,]    1
[3,]    1
[4,]    1
[5,]    1
[6,]    1
Beta: 
(Intercept)           Z 
   4.732139          NA 
Std Devs: (survival object) 
[1] 4.088513

 ## MLE Estimates 
 (Intercept)  Z  stdev
      4.9031 NA 3.7365
      4.7100 NA 3.9266
      4.6552 NA 3.8500
      4.8211 NA 3.9371
      4.7321 NA 4.0885
## Uniform Imputation Range 
           [,1] [,2]
unif_lower "NA" "NA"
unif_upper "NA" "NA"
## Detection Limit: 0.9244609 
```
I added the model, X, and Z in "verbose" so we can see what is happening. 

With no covariates, the function has made it an intercept (or a vector of ones).  In short, the output from survival::survreg() function has changed how it handles the data. Originally, when Z is null, the `impute.boot()` changed Z to be a vector of 1's ,  and everything worked out. Now, the model matrix of survival regression is the intercept and a vector of 1's. With the second column being a linear dependency of the first, the coefficient is missing, and therefore, the imputed values are missing (NA's). The total.miss, consequently, has a missing value.  Therefore, the solution would be to remove a vector of 1's so there is only one coefficient from survival regression to impute the values. 

Here is my info:
```{r}
 sessioninfo::package_info(c("miWQS", "survival"), dependencies = FALSE)
# package  version date (UTC) lib source
# miWQS    0.4.4   2021-04-02 [1] CRAN (R 4.3.0)
# survival   3.5-7   2023-08-14 [1] CRAN (R 4.3.2)
```

An updated version of **miWQS** should be available soon.

**Comment by phargarten2** [comment]
Meaghan Hall:  I came across your R code for impute.boot (miWQS) on github (https://github.com/cran/miWQS/blob/master/R/impute_boot.R). Thank you for this! I have been trying to use impute.boot for one of my projects and am encountering an error when I set Z=NULL. This is the error message I get:
![image](https://github.com/phargarten2/miWQS/assets/17706062/35bfb3e2-1f8f-4e23-a2a2-79eca4dae4ef)

When looking into this, I saw that some other users may be experiencing the same problem. I am wondering if you have encountered any issues like this and if you might have any suggestions as to how to resolve this error?

I am glad to hear that an updated version of miWQS will be available soon! In the meantime, would it be appropriate to downgrade my R to an older version where this function worked?
Any guidance would be much appreciated.

![image](https://github.com/phargarten2/miWQS/assets/17706062/20d5c3f2-d62e-44b3-b802-09f4fef85c04)

**Comment by phargarten2** [comment]
Meaghan: I am glad to hear that an updated version of miWQS will be available soon! In the meantime, would it be appropriate to downgrade my R to an older version where this function worked?

**Comment by phargarten2** [comment]
Meaghan: I tried installing R version 4.2.1 and that also seemed to solve the problem - I was able to run the imputation without any issues.

**Comment by phargarten2** [comment]
Thank you.  You may be onto something here. This function doesn't work because the `survreg()` output from the survival package has changed.  Specifically, the intercept is now included in the survival regression model. You can see what elements of the model are saved in the `impute.Lubin()` function.

If you download an earlier version of the survival package (you don't necessarily need an older version of R), you could use this function. However, I don't know which version of the survival package the change was made, and I am a little short on time right now to figure it out. You can look at the news file  (https://cran.r-project.org/web/packages/survival/index.html),  or ask them when their model changed. You can also download the survival package version listed on the DESCRIPTION file on miWQS page (version 3.1-12), and the function should work.

**Comment by phargarten2** [comment]
Please see the updated miWQS version on GitHub.
